### ISSUE TITLE
Document testing?

### ISSUE THREAD

**Issue by shuhaowu** [maxcountryman/flask-seasurf#30]
The fact that you can disable testing with `app.config["TESTING"] = True` is amazing.

I'm not sure about the security implementations but please document this in the official documentations.

**Comment by Dagur** [comment]
Has this changed at all since this was posted? Can I set CSRF_DISABLE during testing?

**Comment by maxcountryman** [comment]
@Dagur the relevant code hasn't changed. We probably should be checking these values directly, rather than setting up only in `init_app`.

**Comment by Dagur** [comment]
Thanks! Until then I have found a way around this by setting _csrf_disable directly.
