### ISSUE TITLE
Option to disable referer checks?

### ISSUE THREAD

**Issue by 12cel5** [maxcountryman/flask-seasurf#46]
Could an option be added to disable the `referer` check? I already have CSRF tokens attached to all forms and don't see the need to check the referer. I'd like to turn referrers off altogether with the new [referrer policy](http://www.w3.org/TR/referrer-policy/) meta tag but I can't due to seasurf checking them if the site uses https.

**Comment by maxcountryman** [comment]
I'm open to pull requests.

**Comment by alanhamlett** [comment]
Should we offer the ability to check `Origin` header matching a pre-defined hostname (`CSRF_COOKIE_DOMAIN`) and fallback to checking `Referer` header when `Origin` is not present? That would improve support for browsers and sites wanting to disable `Referer` header, without making the website less secure.
