### ISSUE TITLE
Disable CSRF protection in all views by default

### ISSUE THREAD

**Issue by Alexmod** [maxcountryman/flask-seasurf#50]
Hi,
How to disable CSRF protection in all views by default and then selectively protect only what I need?

**Comment by maxcountryman** [comment]
Set `SEASURF_INCLUDE_OR_EXEMPT_VIEWS` to `"include"` and then decorate the views you'd like to include for validation.

**Comment by Alexmod** [comment]
I added.
                         
<code>app.config['SEASURF_INCLUDE_OR_EXEMPT_VIEWS'] = 'include' </code>                  
<code>csrf = SeaSurf(app)   </code>  

Everything works. Thank you!
