### ISSUE TITLE
Add MANIFEST.in with link to LICENSE

### ISSUE THREAD

**Issue by pmlandwehr** [maxcountryman/flask-seasurf#61]
I've put together a build of `Flask-SeaSurf` for conda-forge. (https://github.com/conda-forge/staged-recipes/pull/1519) It'd be good to include a hard link to the license file in the build, but doing so requires that the license file be explicitly referenced in a `MANIFEST.in` file so that the license gets bundled in the source distribution.

**Comment by maxcountryman** [comment]
Thanks!
