### ISSUE TITLE
CORS and CSRF

### ISSUE THREAD

**Issue by pts-davidpark** [maxcountryman/flask-seasurf#74]
If I have specified 3rd party origins (cors) access to particular views, wouldn't the referrer checking (in https) always return a 403 because the origins would never match? In short, I would have to disable csrf protection for those views

**Comment by jasco** [comment]
It appears that the referrer checking _does_ allow for the domain specified in the origin header.
https://github.com/maxcountryman/flask-seasurf/blob/master/flask_seasurf.py#L260

Note, I have not used the package yet.  I am just passing through to see if it meets my needs.

**Comment by maxcountryman** [comment]
Further explanation [here](https://github.com/maxcountryman/flask-seasurf/blob/2ec4cee44e4a703a51e2739091184f044e6d2df5/flask_seasurf.py#L283-L287).
