### ISSUE TITLE
Updated Pypi release

### ISSUE THREAD

**Issue by jasco** [maxcountryman/flask-seasurf#75]
The last release to pypi was 0.2.2 on 3/16/2016.  It looks like some of the commits since then are nice to have published.  Is there another release planned?

**Comment by crazyguitar** [comment]
Hi,
Is there any plan to release 0.2.3 to pypi?

**Comment by rkerr** [comment]
+1 seems a bit odd it's released here but not pypi. For anyone else struggling with this it might be worth noting you can have pip pull 0.2.3 direct from github by using:

`-e git://github.com/maxcountryman/flask-seasurf.git@0.2.3#egg=flask_seasurf`

In requirements.txt

**Comment by ShreyGupta19** [comment]
+1 for a release on PyPI! Was confused as to why my samesite cookie option wasn't being used until I saw that 0.2.3 wasn't available on PyPI.

**Comment by BKPepe** [comment]
@alanhamlett , @maxcountryman Could you please look at this issue?

**Comment by maxcountryman** [comment]
If someone would like to take on the work of publishing to PyPI via GitHub Actions I'd be happy to add the necessary secrets and tag a new release.

**Comment by BKPepe** [comment]
Shouldn't this work https://github.com/marketplace/actions/pypi-publish ?

**Comment by maxcountryman** [comment]
It might, but the workflow will need to be setup (specifically for tags).

**Comment by gaborfeher** [comment]
@maxcountryman do you see any chance of making a new release using #98 ?

**Comment by maxcountryman** [comment]
Yep let's give it a shot @gaborfeher.

**Comment by maxcountryman** [comment]
I believe we're pretty current.
