### ISSUE TITLE
Python Code Injection

### ISSUE THREAD

**Issue by edmacke** [maxcountryman/flask-seasurf#90]
While running a dynamic scan against an app protected by seasurf, Burp Suite Pro flagged an issue with the CSRF token.

For a GET operation, it altered the _csrf_token value as below, and raised an alarm when the app didn't respond for > 20 seconds, indicating the sleep operation was successfully run, indicating a Python injection vulnerability.

Cookie: _csrf_token=eval(compile('for%20x%20in%20range(1)%3a%5cn%20import%20time%5cn%20time.sleep(20)'%2c'a'%2c'single'));

**Comment by maxcountryman** [comment]
Thanks for the report—I haven’t looked at this code in many years, but I’ll happily patch and release any security issues.

Also this might be something that should be reported upstream to Django, if it hasn’t already been fixed.

**Comment by edmacke** [comment]
Honestly, I'm not 100% where the issue actually lies. It's a little weird, because Burp is modifying the _csrf_token cookie value to be a value of "eval(compile(...code...))", and the "...code..." is code that, if executed, should cause a 20-second delay.

But, as far as I know, the only way that could actually cause a 20-second delay is if that string were passed to an eval() method. And I don't see where that is being done.

Also, if the string were being passed to an eval() method, setting _csrf_token="...code..." should be enough to make that happen. In other words, if somewhere there was something like:

**eval(_csrf_token)**

then

**eval(...code...)**

would cause that injected code to be evaluated and run and cause a 20-second delay. But the injected value isn't just "...code...", it's "eval(compile(...code...))" which means somewhere there's something like:

**eval(eval(compile(...code...)))**

I'm at a loss to see how a string cookie value of "eval(compile(...code...))" is actually leading to execution of "...code..."

**Comment by maxcountryman** [comment]
It seems odd to me too. I’m at work and haven’t had a chance to look at it too deeply. One thing that jumps to mind is Jinja.

**Comment by alanhamlett** [comment]
I'm not able to reproduce this with that csrf token cookie value. Most likely it was a false-positive. If you re-run that request does the app consistently take over 20s to respond? If you change the sleep value from 20 to 1 does the app consistently take 1 second to respond or still over 20 seconds?

**Comment by maxcountryman** [comment]
Is there a unit test that reproduces this issue?

I think it'd also be helpful to know more context here: Python version, Flask version, etc.

**Comment by edmacke** [comment]
No unit test that I know of, just the Burp Suite Pro test. I'm trying to get more details on that... I'm not 100% sure it's not a false positive... 

Here's my requirements.txt file, if that helps, running under Python 3.7.3
blinker==1.4
click==7.0
duo-client==4.2.0
flask-ldap3-login==0.9.16
flask-login==0.4.1
flask-seasurf==0.2.2
flask-talisman==0.7.0
flask-wtf==0.14.2
flask==1.0.3
gunicorn==19.9.0
itsdangerous==1.1.0
jinja2==2.10.1
ldap3==2.6
markupsafe==1.1.1
pyasn1==0.4.5
pytz==2019.1
six==1.12.0
wtforms==2.2.1

**Comment by brukhabtu** [comment]
Any news on this? I am having a hard time reproducing this issue myself.

**Comment by edmacke** [comment]
P {margin-top:0;margin-bottom:0;} 



I'm wondering if it was a false positive. I tried running the same test in isolation, and no vulnerability was found.

**Comment by alanhamlett** [comment]
> I tried running the same test in isolation

Are you able to re-run the test on the same server as first reported? If you see inconsistencies in response times with the original server we can close this issue as false positive.

**Comment by alanhamlett** [comment]
Closing unless can be reproduced.
